#!/usr/bin/env bash
# Generate .env.worktree with computed port values and worktree-specific env
# Usage: generate-worktree-env.sh [--name <worktree-name>] [--offset <number>]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Base ports
BASE_PG_PORT=5432
BASE_API_PORT=8080
BASE_WEB_PORT=4000
BASE_LANDING_PORT=4321

PROJECT_OFFSET=55
offset=0
manual_offset=false
name=""
auto_detect=true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      name="${2:-}"
      auto_detect=false
      shift 2
      ;;
    --offset)
      offset="${2:-0}"
      manual_offset=true
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

# Auto-detect branch name if --name not provided
if [[ "$auto_detect" == "true" && -z "$name" ]]; then
  if ! git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Error: not in a git repository and --name not provided" >&2
    exit 1
  fi
  name="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null)"
  if [[ -z "$name" ]]; then
    echo "Error: could not detect branch name" >&2
    exit 1
  fi
fi

# Compute offset from name if provided
if [[ -n "$name" && "$name" != "main" && "$name" != "master" ]]; then
  checksum="$(printf "%s" "$name" | cksum | awk '{print $1}')"
  offset=$(( (checksum % 1000) + 27 ))
fi

# Apply project-specific offset when not manually provided
if [[ "$manual_offset" == "false" ]]; then
  offset=$((offset + PROJECT_OFFSET))
fi

# Validate offset
if ! [[ "$offset" =~ ^[0-9]+$ ]]; then
  echo "Error: offset must be a non-negative integer, got: $offset" >&2
  exit 1
fi

# Compute ports
PG_PORT=$((BASE_PG_PORT + offset))
API_PORT=$((BASE_API_PORT + offset))
WEB_PORT=$((BASE_WEB_PORT + offset))
LANDING_PORT=$((BASE_LANDING_PORT + offset))

cat > "$REPO_ROOT/.env.worktree" << EOF
# Generated by scripts/generate-worktree-env.sh - do not edit manually
# Offset: $offset${name:+ (from: $name)}

PG_PORT=$PG_PORT
API_PORT=$API_PORT
WEB_PORT=$WEB_PORT
LANDING_PORT=$LANDING_PORT

# URLs
API_URL=http://localhost:$API_PORT
WEB_URL=http://localhost:$WEB_PORT
LANDING_URL=http://localhost:$LANDING_PORT

# Docker Compose project name (prevents network collisions across projects/worktrees)
COMPOSE_PROJECT_NAME=template_${name:-default}
EOF

echo "Generated .env.worktree (offset: $offset)"
