// ── AUTO-GENERATED BY nestjs-trpc-v2 ──
// Regenerate by restarting the API server
// DO NOT EDIT MANUALLY

import { initTRPC } from "@trpc/server";
import superjson from "superjson";

const t = initTRPC.context().create({
  transformer: superjson,
});
const publicProcedure = t.procedure;

const appRouter = t.router({
  health: t.router({
    ping: publicProcedure.query(async () => "pong"),
  }),
});

export type AppRouter = typeof appRouter;
