-- ── Create enum types ─────────────────────────────────────────
-- Generated by script from branded constants


-- ── Swap varchar columns to pgEnum types ──────────────────────

ALTER TABLE animals ALTER COLUMN state_code TYPE state_code USING state_code::state_code;
ALTER TABLE animals ALTER COLUMN sex TYPE sex USING sex::sex;
ALTER TABLE animals ALTER COLUMN birth_type TYPE birth_type USING birth_type::birth_type;
ALTER TABLE animals ALTER COLUMN status TYPE animal_status USING status::animal_status;
ALTER TABLE animals ALTER COLUMN parent_type TYPE parent_type USING parent_type::parent_type;
ALTER TABLE birth_notifications ALTER COLUMN source TYPE event_source USING source::event_source;
ALTER TABLE birth_notifications ALTER COLUMN status TYPE birth_notification_status USING status::birth_notification_status;
ALTER TABLE movements ALTER COLUMN type TYPE movement_type USING type::movement_type;
ALTER TABLE movements ALTER COLUMN death_cause TYPE death_cause USING death_cause::death_cause;
ALTER TABLE pasture_declarations ALTER COLUMN pasture_type TYPE pasture_type USING pasture_type::pasture_type;
ALTER TABLE slaughter_records ALTER COLUMN mass_type TYPE slaughter_mass_type USING mass_type::slaughter_mass_type;
ALTER TABLE ear_tags ALTER COLUMN state_code TYPE state_code USING state_code::state_code;
ALTER TABLE ear_tags ALTER COLUMN status TYPE ear_tag_status USING status::ear_tag_status;
ALTER TABLE ear_tag_orders ALTER COLUMN status TYPE ear_tag_order_status USING status::ear_tag_order_status;
ALTER TABLE ear_tag_replacements ALTER COLUMN reason TYPE ear_tag_replacement_reason USING reason::ear_tag_replacement_reason;
ALTER TABLE ear_tag_replacements ALTER COLUMN status TYPE ear_tag_replacement_status USING status::ear_tag_replacement_status;
ALTER TABLE ear_tag_allocations ALTER COLUMN distribution_method TYPE distribution_method USING distribution_method::distribution_method;
ALTER TABLE ear_tag_allocations ALTER COLUMN status TYPE allocation_status USING status::allocation_status;
ALTER TABLE ear_tag_types ALTER COLUMN category TYPE tag_category USING category::tag_category;
ALTER TABLE farms ALTER COLUMN type TYPE farm_type USING type::farm_type;
ALTER TABLE farms ALTER COLUMN verification_status TYPE verification_status USING verification_status::verification_status;
ALTER TABLE farms ALTER COLUMN data_source TYPE data_source USING data_source::data_source;
ALTER TABLE farm_subjects ALTER COLUMN role TYPE subject_role USING role::subject_role;
ALTER TABLE sync_errors ALTER COLUMN error_type TYPE sync_error_type USING error_type::sync_error_type;
ALTER TABLE notifications ALTER COLUMN type TYPE notification_type USING type::notification_type;
ALTER TABLE notifications ALTER COLUMN category TYPE notification_category USING category::notification_category;
ALTER TABLE notifications ALTER COLUMN priority TYPE notification_priority USING priority::notification_priority;
ALTER TABLE notifications ALTER COLUMN status TYPE notification_status USING status::notification_status;
ALTER TABLE notifications ALTER COLUMN source TYPE event_source USING source::event_source;
ALTER TABLE notification_templates ALTER COLUMN type TYPE notification_type USING type::notification_type;
ALTER TABLE notification_templates ALTER COLUMN category TYPE notification_category USING category::notification_category;
ALTER TABLE notification_templates ALTER COLUMN priority TYPE notification_priority USING priority::notification_priority;
ALTER TABLE notification_preferences ALTER COLUMN category TYPE notification_category USING category::notification_category;
ALTER TABLE audit_log ALTER COLUMN action TYPE audit_action USING action::audit_action;
ALTER TABLE audit_log ALTER COLUMN source TYPE event_source USING source::event_source;
ALTER TABLE organizations ALTER COLUMN org_type TYPE org_type USING org_type::org_type;
ALTER TABLE modules ALTER COLUMN type TYPE module_type USING type::module_type;
ALTER TABLE modules ALTER COLUMN severity TYPE severity USING severity::severity;
