/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Sessions {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  name: string;
  updatedAt: Timestamp;
}

export interface Todos {
  completed: boolean;
  createdAt: Timestamp;
  id: Generated<string>;
  title: string;
  updatedAt: Timestamp;
  userId: string;
}

export interface Verifications {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface DB {
  accounts: Accounts;
  sessions: Sessions;
  todos: Todos;
  users: Users;
  verifications: Verifications;
}
