export const MOVEMENT_ERRORS = {
  NOT_FOUND: "MOVEMENT_NOT_FOUND",
  INVALID_DATES: "MOVEMENT_INVALID_DATES",
  INVALID_INPUT: "MOVEMENT_INVALID_INPUT",
  FORBIDDEN: "MOVEMENT_FORBIDDEN",
  SAME_FARM: "MOVEMENT_SAME_FARM_ERROR",
  ANIMAL_NOT_ALIVE: "MOVEMENT_ANIMAL_NOT_ALIVE",
  ANIMAL_NOT_ON_FARM: "MOVEMENT_ANIMAL_NOT_ON_FARM",
  DEATH_CAUSE_REQUIRED: "MOVEMENT_DEATH_CAUSE_REQUIRED",
  STILLBORN_THRESHOLD: "MOVEMENT_STILLBORN_THRESHOLD",
  PASTURE_ANIMAL_NOT_HOME: "MOVEMENT_PASTURE_ANIMAL_NOT_HOME",
  PASTURE_AUTO_TRANSFER: "MOVEMENT_PASTURE_AUTO_TRANSFER",
  PASTURE_INVALID_DEPARTURE: "MOVEMENT_PASTURE_INVALID_DEPARTURE",
  SLAUGHTER_MIN_AGE: "MOVEMENT_SLAUGHTER_MIN_AGE",
  UNREGISTERED_FARM: "MOVEMENT_UNREGISTERED_FARM",
  IMPORT_ALREADY_REGISTERED: "MOVEMENT_IMPORT_ALREADY_REGISTERED",
  EXPORT_ANIMAL_NOT_FOUND: "MOVEMENT_EXPORT_ANIMAL_NOT_FOUND",
  FARM_LOCKED: "MOVEMENT_FARM_LOCKED",
  WITHDRAWAL_PERIOD_ACTIVE: "MOVEMENT_WITHDRAWAL_PERIOD_ACTIVE",
  TRANSPORT_WELFARE_MAX_EXCEEDED: "MOVEMENT_TRANSPORT_WELFARE_MAX_EXCEEDED",
  TRANSPORT_WELFARE_REST_STOP_REQUIRED: "MOVEMENT_TRANSPORT_WELFARE_REST_STOP_REQUIRED",
} as const;

export type MovementErrorCode =
  (typeof MOVEMENT_ERRORS)[keyof typeof MOVEMENT_ERRORS];

export class MovementError extends Error {
  constructor(
    public readonly code: MovementErrorCode,
    public readonly context?: Record<string, unknown>,
  ) {
    super(code);
    this.name = "MovementError";
  }
}

export const movementErr = (
  code: MovementErrorCode,
  context?: Record<string, unknown>,
): MovementError => new MovementError(code, context);
