export default {
  "iso27701-2025-gap-analysis": { title: "ISO 27701:2025 / 27001:2022 Gap Analysis" },
  "isms-policy": { title: "ISMS / PIMS Policy (Rocky)" },
  "rocky-ropa": { title: "Records of Processing Activities (RoPA)" },
  "rocky-erasure-retention-procedure": { title: "Erasure & Retention Procedure" },
  "rocky-lawful-basis-register": { title: "Lawful Basis Register" },
  "rocky-privacy-notice": { title: "Privacy Notice" },
  "rocky-dpia-health": { title: "DPIA — Health Domain" },
  "rocky-breach-notification-procedure": { title: "Breach Notification Procedure" },
  "rocky-processor-register": { title: "Processor / Sub-processor Register" },
  "rocky-dsr-procedure": { title: "Data Subject Rights (DSR) Procedure" },
  "rocky-toms": { title: "Technical & Organizational Measures (TOMs)" },
  "rocky-withdrawal-recall-procedure": { title: "Withdrawal & Recall Procedure (Art 19)" },
  "rocky-cookie-notice": { title: "Cookie & Tracking Notice" },
  "rocky-dpa": { title: "Data Processing Agreement (DPA) — Art 28" },
  "rocky-retention-schedule": { title: "Retention Schedule" },
  "rocky-automated-decision-making": { title: "Automated Decision-Making & Profiling" },
  "rocky-international-transfer-assessment": { title: "International Transfer Assessment" },
  "rocky-soa": { title: "Statement of Applicability (SoA)" },
  "rocky-risk-assessment": { title: "Information Security Risk Assessment" },
  "rocky-risk-treatment-plan": { title: "Risk Treatment Plan" },
  "rocky-internal-audit-procedure": { title: "Internal Audit Procedure" },
  "eu-b2b-procurement-pack": { title: "EU B2B Procurement Compliance Pack" },
  "MACEDONIAN_LPDP": { title: "Macedonian LPDP + GDPR + ISO 27701 (MK)" },
  } as const;
