/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { animalParents, animals } from "../schema/an/animals.js";
import { birthNotifications } from "../schema/an/birth-notifications.js";
import { earTags } from "../schema/an/ear-tags.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const animalsSelectSchema = createSelectSchema(animals);
export const animalsInsertSchema = createInsertSchema(animals);

export const animalParentsSelectSchema = createSelectSchema(animalParents);
export const animalParentsInsertSchema = createInsertSchema(animalParents);

export const earTagsSelectSchema = createSelectSchema(earTags);
export const earTagsInsertSchema = createInsertSchema(earTags);

export const birthNotificationsSelectSchema = createSelectSchema(birthNotifications);
export const birthNotificationsInsertSchema = createInsertSchema(birthNotifications);
