/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { archiveDocuments } from "../schema/an/archive-documents.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const archiveDocumentsSelectSchema = createSelectSchema(archiveDocuments);
export const archiveDocumentsInsertSchema = createInsertSchema(archiveDocuments);
