/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { auditLog } from "../schema/sm/audit-log.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const auditLogSelectSchema = createSelectSchema(auditLog);
export const auditLogInsertSchema = createInsertSchema(auditLog);
