/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { errorCorrections } from "../schema/an/error-corrections.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const errorCorrectionsSelectSchema = createSelectSchema(errorCorrections);
export const errorCorrectionsInsertSchema = createInsertSchema(errorCorrections);
