/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { earTagAllocations } from "../schema/an/ear-tag-allocations.js";
import { earTagOrders } from "../schema/an/ear-tag-orders.js";
import { earTagReplacements } from "../schema/an/ear-tag-replacements.js";
import { earTagTakeovers } from "../schema/an/ear-tag-takeovers.js";
import { earTagTypes } from "../schema/an/ear-tag-types.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const earTagAllocationsSelectSchema = createSelectSchema(earTagAllocations);
export const earTagAllocationsInsertSchema = createInsertSchema(earTagAllocations);

export const earTagOrdersSelectSchema = createSelectSchema(earTagOrders);
export const earTagOrdersInsertSchema = createInsertSchema(earTagOrders);

export const earTagReplacementsSelectSchema = createSelectSchema(earTagReplacements);
export const earTagReplacementsInsertSchema = createInsertSchema(earTagReplacements);

export const earTagTakeoversSelectSchema = createSelectSchema(earTagTakeovers);
export const earTagTakeoversInsertSchema = createInsertSchema(earTagTakeovers);

export const earTagTypesSelectSchema = createSelectSchema(earTagTypes);
export const earTagTypesInsertSchema = createInsertSchema(earTagTypes);
