/**
 * ⛔ AUTO-GENERATED factory — DO NOT EDIT MANUALLY.
 *
 * drizzle-orm/zod schema factory with date coercion and bigint handling.
 *
 * ## Date Coercion Architecture (Two-Layer Truth)
 *
 * **Layer 2 (this factory):** `coerce: { date: true }` means every
 * `createSelectSchema` / `createInsertSchema` / `createUpdateSchema` output
 * uses `z.coerce.date()` with input type `Date | string`. This is **tolerant
 * coercion** — it accepts whatever the DB/JSON serialization layer gives us.
 * Postgres rows pass through tRPC, queues, and JSONB round-trips where `Date`
 * objects become strings. Pure `z.date()` would reject them.
 *
 * **Layer 1 (API validators):** When an L1 schema extends a Dumb Zod date field,
 * it uses `z.coerce.date<string>()` — the `<string>` generic locks the wire
 * input type to `string`. See ADR 0010 for the full two-layer reasoning.
 *
 * **Key insight:** The two coercions are NOT redundant. L2 = "I tolerate what
 * the DB/JSON gives me." L1 = "I demand exactly a string from the outside."
 *
 * ## Bigint handling
 *
 * Columns defined as `bigint({ mode: 'number' })` in Drizzle schemas
 * automatically map to `z.number()`. No extra config needed.
 *
 * ## Auto-generation status
 *
 * The per-domain files (e.g., `animal.ts`, `farm.ts`) are generated by
 * `scripts/generate-dumb-zod.mjs` — they scan `packages/database/src/schema/`
 * for `pgTable` exports and emit `createSelectSchema` / `createInsertSchema`
 * calls. The `_domain-map.ts` config file maps schema files to domain names.
 * JSONB overrides live in `_overrides.ts` — the only hand-written file in this
 * directory.
 *
 * @see ADR 0010 apps/docs/content/ADR/0010-date-coercion-architecture.md
 * @see https://orm.drizzle.team/docs/zod
 */

import { createSchemaFactory } from "drizzle-orm/zod";

const factory = createSchemaFactory({
	coerce: {
		date: true,
	},
});

/**
 * Type-annotated wrappers.
 *
 * The factory's inferred return type references drizzle-orm internal paths
 * (schema.types.internal.cjs), which causes TS2883 "cannot be named without
 * reference to X" errors at every call site.
 *
 * By explicitly typing these exports with the PUBLIC interface types from
 * drizzle-orm/zod, TypeScript uses the public path for inference at call sites.
 */
export const createSelectSchema = factory.createSelectSchema;
export const createInsertSchema = factory.createInsertSchema;
export const createUpdateSchema = factory.createUpdateSchema;
