/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { addresses, adminUnits, communes, states, zipCodes } from "../schema/hk/addresses.js";
import { farmBooks } from "../schema/hk/farm-books.js";
import { farmSubjects } from "../schema/hk/farm-subjects.js";
import { farms } from "../schema/hk/farms.js";
import { subjects } from "../schema/hk/subjects.js";
import { syncErrors } from "../schema/hk/sync-errors.js";
import { vsAssignments } from "../schema/hk/vs-assignments.js";
import { vsContracts } from "../schema/hk/vs-contracts.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const statesSelectSchema = createSelectSchema(states);
export const statesInsertSchema = createInsertSchema(states);

export const zipCodesSelectSchema = createSelectSchema(zipCodes);
export const zipCodesInsertSchema = createInsertSchema(zipCodes);

export const communesSelectSchema = createSelectSchema(communes);
export const communesInsertSchema = createInsertSchema(communes);

export const adminUnitsSelectSchema = createSelectSchema(adminUnits);
export const adminUnitsInsertSchema = createInsertSchema(adminUnits);

export const addressesSelectSchema = createSelectSchema(addresses);
export const addressesInsertSchema = createInsertSchema(addresses);

export const farmsSelectSchema = createSelectSchema(farms);
export const farmsInsertSchema = createInsertSchema(farms);

export const farmSubjectsSelectSchema = createSelectSchema(farmSubjects);
export const farmSubjectsInsertSchema = createInsertSchema(farmSubjects);

export const subjectsSelectSchema = createSelectSchema(subjects);
export const subjectsInsertSchema = createInsertSchema(subjects);

export const farmBooksSelectSchema = createSelectSchema(farmBooks);
export const farmBooksInsertSchema = createInsertSchema(farmBooks);

export const vsContractsSelectSchema = createSelectSchema(vsContracts);
export const vsContractsInsertSchema = createInsertSchema(vsContracts);

export const vsAssignmentsSelectSchema = createSelectSchema(vsAssignments);
export const vsAssignmentsInsertSchema = createInsertSchema(vsAssignments);

export const syncErrorsSelectSchema = createSelectSchema(syncErrors);
export const syncErrorsInsertSchema = createInsertSchema(syncErrors);
