/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { diseaseEventProcedures } from "../schema/hd/disease-event-procedures.js";
import { diseaseEvents } from "../schema/hd/disease-events.js";
import { diseaseSpeciesApplicability } from "../schema/hd/disease-species-applicability.js";
import { diseases } from "../schema/hd/diseases.js";
import { labTests } from "../schema/hd/lab-tests.js";
import { speciesGroups } from "../schema/hd/species-groups.js";
import { treatments } from "../schema/hd/treatments.js";
import { vaccinations } from "../schema/hd/vaccinations.js";
import { vaccineBatches } from "../schema/hd/vaccine-batches.js";
import { vaccineDiseases } from "../schema/hd/vaccine-diseases.js";
import { vaccines } from "../schema/hd/vaccines.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const diseasesSelectSchema = createSelectSchema(diseases);
export const diseasesInsertSchema = createInsertSchema(diseases);

export const vaccinesSelectSchema = createSelectSchema(vaccines);
export const vaccinesInsertSchema = createInsertSchema(vaccines);

export const vaccineBatchesSelectSchema = createSelectSchema(vaccineBatches);
export const vaccineBatchesInsertSchema = createInsertSchema(vaccineBatches);

export const vaccinationsSelectSchema = createSelectSchema(vaccinations);
export const vaccinationsInsertSchema = createInsertSchema(vaccinations);

export const treatmentsSelectSchema = createSelectSchema(treatments);
export const treatmentsInsertSchema = createInsertSchema(treatments);

export const labTestsSelectSchema = createSelectSchema(labTests);
export const labTestsInsertSchema = createInsertSchema(labTests);

export const vaccineDiseasesSelectSchema = createSelectSchema(vaccineDiseases);
export const vaccineDiseasesInsertSchema = createInsertSchema(vaccineDiseases);

export const speciesGroupsSelectSchema = createSelectSchema(speciesGroups);
export const speciesGroupsInsertSchema = createInsertSchema(speciesGroups);

export const diseaseSpeciesApplicabilitySelectSchema = createSelectSchema(diseaseSpeciesApplicability);
export const diseaseSpeciesApplicabilityInsertSchema = createInsertSchema(diseaseSpeciesApplicability);

export const diseaseEventsSelectSchema = createSelectSchema(diseaseEvents);
export const diseaseEventsInsertSchema = createInsertSchema(diseaseEvents);

export const diseaseEventProceduresSelectSchema = createSelectSchema(diseaseEventProcedures);
export const diseaseEventProceduresInsertSchema = createInsertSchema(diseaseEventProcedures);
