/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { inspections } from "../schema/an/inspections.js";
import { riskAnalyses } from "../schema/an/risk-analyses.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const inspectionsSelectSchema = createSelectSchema(inspections);
export const inspectionsInsertSchema = createInsertSchema(inspections);

export const riskAnalysesSelectSchema = createSelectSchema(riskAnalyses);
export const riskAnalysesInsertSchema = createInsertSchema(riskAnalyses);
