/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { animalGeofenceEvents } from "../schema/an/animal-geofence-events.js";
import { geofences } from "../schema/an/geofences.js";
import { iotDevices } from "../schema/an/iot-devices.js";
import { pdaDevices } from "../schema/an/pda-devices.js";
import { sensorReadings } from "../schema/an/sensor-readings.js";
import { settlements } from "../schema/an/settlements.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const iotDevicesSelectSchema = createSelectSchema(iotDevices);
export const iotDevicesInsertSchema = createInsertSchema(iotDevices);

export const sensorReadingsSelectSchema = createSelectSchema(sensorReadings);
export const sensorReadingsInsertSchema = createInsertSchema(sensorReadings);

export const geofencesSelectSchema = createSelectSchema(geofences);
export const geofencesInsertSchema = createInsertSchema(geofences);

export const animalGeofenceEventsSelectSchema = createSelectSchema(animalGeofenceEvents);
export const animalGeofenceEventsInsertSchema = createInsertSchema(animalGeofenceEvents);

export const pdaDevicesSelectSchema = createSelectSchema(pdaDevices);
export const pdaDevicesInsertSchema = createInsertSchema(pdaDevices);

export const settlementsSelectSchema = createSelectSchema(settlements);
export const settlementsInsertSchema = createInsertSchema(settlements);
