/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { businessRules, codeTables, moduleBusinessRules, modules, systemParameters } from "../schema/sm/modules.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const modulesSelectSchema = createSelectSchema(modules);
export const modulesInsertSchema = createInsertSchema(modules);

export const businessRulesSelectSchema = createSelectSchema(businessRules);
export const businessRulesInsertSchema = createInsertSchema(businessRules);

export const moduleBusinessRulesSelectSchema = createSelectSchema(moduleBusinessRules);
export const moduleBusinessRulesInsertSchema = createInsertSchema(moduleBusinessRules);

export const codeTablesSelectSchema = createSelectSchema(codeTables);
export const codeTablesInsertSchema = createInsertSchema(codeTables);

export const systemParametersSelectSchema = createSelectSchema(systemParameters);
export const systemParametersInsertSchema = createInsertSchema(systemParameters);
