/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { importExportRecords } from "../schema/an/import-export-records.js";
import { movements } from "../schema/an/movements.js";
import { pastureDeclarations } from "../schema/an/pasture.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const movementsSelectSchema = createSelectSchema(movements);
export const movementsInsertSchema = createInsertSchema(movements);

export const pastureDeclarationsSelectSchema = createSelectSchema(pastureDeclarations);
export const pastureDeclarationsInsertSchema = createInsertSchema(pastureDeclarations);

export const importExportRecordsSelectSchema = createSelectSchema(importExportRecords);
export const importExportRecordsInsertSchema = createInsertSchema(importExportRecords);
