/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { eventSubscriptions } from "../schema/events/event-subscriptions.js";
import { notificationDeliveries } from "../schema/events/notification-deliveries.js";
import { reminders } from "../schema/events/reminders.js";
import { notificationPreferences } from "../schema/sm/notification-preferences.js";
import { notificationTemplates } from "../schema/sm/notification-templates.js";
import { notifications } from "../schema/sm/notifications.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const notificationsSelectSchema = createSelectSchema(notifications);
export const notificationsInsertSchema = createInsertSchema(notifications);

export const notificationPreferencesSelectSchema = createSelectSchema(notificationPreferences);
export const notificationPreferencesInsertSchema = createInsertSchema(notificationPreferences);

export const notificationTemplatesSelectSchema = createSelectSchema(notificationTemplates);
export const notificationTemplatesInsertSchema = createInsertSchema(notificationTemplates);

export const notificationDeliveriesSelectSchema = createSelectSchema(notificationDeliveries);
export const notificationDeliveriesInsertSchema = createInsertSchema(notificationDeliveries);

export const eventSubscriptionsSelectSchema = createSelectSchema(eventSubscriptions);
export const eventSubscriptionsInsertSchema = createInsertSchema(eventSubscriptions);

export const remindersSelectSchema = createSelectSchema(reminders);
export const remindersInsertSchema = createInsertSchema(reminders);
