/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { orgAreas, organizations } from "../schema/sm/organizations.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const organizationsSelectSchema = createSelectSchema(organizations);
export const organizationsInsertSchema = createInsertSchema(organizations);

export const orgAreasSelectSchema = createSelectSchema(orgAreas);
export const orgAreasInsertSchema = createInsertSchema(orgAreas);
