/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { outboxEvents } from "../schema/sm/outbox-events.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const outboxEventsSelectSchema = createSelectSchema(outboxEvents);
export const outboxEventsInsertSchema = createInsertSchema(outboxEvents);
