/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { cattlePassports } from "../schema/an/cattle-passports.js";
import { formReprints } from "../schema/an/form-reprints.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const cattlePassportsSelectSchema = createSelectSchema(cattlePassports);
export const cattlePassportsInsertSchema = createInsertSchema(cattlePassports);

export const formReprintsSelectSchema = createSelectSchema(formReprints);
export const formReprintsInsertSchema = createInsertSchema(formReprints);
