/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { permissions, rolePermissions, roles, userRoles } from "../schema/sm/rbac.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const rolesSelectSchema = createSelectSchema(roles);
export const rolesInsertSchema = createInsertSchema(roles);

export const permissionsSelectSchema = createSelectSchema(permissions);
export const permissionsInsertSchema = createInsertSchema(permissions);

export const rolePermissionsSelectSchema = createSelectSchema(rolePermissions);
export const rolePermissionsInsertSchema = createInsertSchema(rolePermissions);

export const userRolesSelectSchema = createSelectSchema(userRoles);
export const userRolesInsertSchema = createInsertSchema(userRoles);
