/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { syncIdempotency } from "../schema/sync.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const syncIdempotencySelectSchema = createSelectSchema(syncIdempotency);
export const syncIdempotencyInsertSchema = createInsertSchema(syncIdempotency);
