/** ⛔ AUTO-GENERATED BY scripts/generate-dumb-zod.mjs ⛔ */
/** DO NOT EDIT. To add a table, update _domain-map.ts and re-run the generator. */

import { deviceTokens } from "../schema/sm/device-tokens.js";
import { userSessions, users } from "../schema/sm/users.js";
import { createInsertSchema, createSelectSchema } from "./factory.js";

export const usersSelectSchema = createSelectSchema(users);
export const usersInsertSchema = createInsertSchema(users);

export const userSessionsSelectSchema = createSelectSchema(userSessions);
export const userSessionsInsertSchema = createInsertSchema(userSessions);

export const deviceTokensSelectSchema = createSelectSchema(deviceTokens);
export const deviceTokensInsertSchema = createInsertSchema(deviceTokens);
