-- Auto-generated migration: Create enum types
-- Based on constants and schema regeneration

CREATE TYPE IF NOT EXISTS admin_roles AS ENUM ('[
    ADMIN_ROLE.SUPER_ADMIN', 'ADMIN_ROLE.VD_ADMIN', 'ADMIN_ROLE.VD_STAFF', '] as const');
CREATE TYPE IF NOT EXISTS allocation_status AS ENUM ('[
  ALLOCATION_STATUS.PENDING', 'ALLOCATION_STATUS.PARTIALLY_FULFILLED', 'ALLOCATION_STATUS.FULFILLED', 'ALLOCATION_STATUS.CANCELLED', '] as const');
CREATE TYPE IF NOT EXISTS allocation_type AS ENUM ('[
	ALLOCATION_TYPE.INITIAL_ALLOCATION', 'ALLOCATION_TYPE.ROUTINE_ALLOCATION', 'ALLOCATION_TYPE.RETURN', '] as const');
CREATE TYPE IF NOT EXISTS animal_status AS ENUM ('[
	ANIMAL_STATUS.ALIVE', 'ANIMAL_STATUS.DEAD', 'ANIMAL_STATUS.SLAUGHTERED', 'ANIMAL_STATUS.SOLD', 'ANIMAL_STATUS.EXPORTED', 'ANIMAL_STATUS.IMPORTED', 'ANIMAL_STATUS.MISSING', 'ANIMAL_STATUS.STILLBORN', '] as const');
CREATE TYPE IF NOT EXISTS approval_action AS ENUM ('[
	APPROVAL_ACTION.APPROVE', 'APPROVAL_ACTION.REJECT', 'APPROVAL_ACTION.REQUEST_CHANGES', '] as const');
CREATE TYPE IF NOT EXISTS audit_action AS ENUM ('[
  AUDIT_ACTION.CREATE', 'AUDIT_ACTION.UPDATE', 'AUDIT_ACTION.DELETE', 'AUDIT_ACTION.LOGIN', 'AUDIT_ACTION.EXPORT', 'AUDIT_ACTION.IMPORT', '] as const');
CREATE TYPE IF NOT EXISTS birth_notification_status AS ENUM ('[
  BIRTH_NOTIFICATION_STATUS.PENDING', 'BIRTH_NOTIFICATION_STATUS.SENT', 'BIRTH_NOTIFICATION_STATUS.FAILED', '] as const');
CREATE TYPE IF NOT EXISTS birth_type AS ENUM ('[
	BIRTH_TYPE.SINGLE', 'BIRTH_TYPE.TWIN', 'BIRTH_TYPE.TRIPLET', 'BIRTH_TYPE.STILLBORN', '] as const');
CREATE TYPE IF NOT EXISTS contingent_type AS ENUM ('[
	CONTINGENT_TYPE.SUPPLIER', 'CONTINGENT_TYPE.VD', 'CONTINGENT_TYPE.VS', '] as const');
CREATE TYPE IF NOT EXISTS data_source AS ENUM ('[
	DATA_SOURCE.AIMCS', 'DATA_SOURCE.HK_IMP', 'DATA_SOURCE.HK_PDA', 'DATA_SOURCE.MOBILE', 'DATA_SOURCE.API', 'DATA_SOURCE.BATCH', '] as const');
CREATE TYPE IF NOT EXISTS death_cause AS ENUM ('[
	DEATH_CAUSE.DEATH_REGISTERED', 'DEATH_CAUSE.DEATH_UNREGISTERED', 'DEATH_CAUSE.DEATH_UNREGISTERED_IMPORT', 'DEATH_CAUSE.STILLBORN', 'DEATH_CAUSE.DEATH_AFTER_BIRTH', '] as const');
CREATE TYPE IF NOT EXISTS delivery_method AS ENUM ('[DELIVERY_METHOD.HK_IMP', 'DELIVERY_METHOD.HK_PDA] as const');
CREATE TYPE IF NOT EXISTS distribution_method AS ENUM ('[
  DISTRIBUTION_METHOD.VD_DELIVERY', 'DISTRIBUTION_METHOD.PICKUP', '] as const');
CREATE TYPE IF NOT EXISTS duplicate_type AS ENUM ('[
	DUPLICATE_TYPE.SINGLE', 'DUPLICATE_TYPE.PAIR', '] as const');
CREATE TYPE IF NOT EXISTS ear_tag_order_status AS ENUM ('[
	EAR_TAG_ORDER_STATUS.DRAFT', 'EAR_TAG_ORDER_STATUS.PENDING', 'EAR_TAG_ORDER_STATUS.APPROVED', 'EAR_TAG_ORDER_STATUS.REJECTED', 'EAR_TAG_ORDER_STATUS.ORDERED', 'EAR_TAG_ORDER_STATUS.PARTIALLY_RECEIVED', 'EAR_TAG_ORDER_STATUS.RECEIVED', 'EAR_TAG_ORDER_STATUS.CANCELLED', '] as const');
CREATE TYPE IF NOT EXISTS ear_tag_replacement_reason AS ENUM ('[
	EAR_TAG_REPLACEMENT_REASON.LOST', 'EAR_TAG_REPLACEMENT_REASON.DAMAGED', 'EAR_TAG_REPLACEMENT_REASON.DEFECTIVE', 'EAR_TAG_REPLACEMENT_REASON.ILLEGIBLE', 'EAR_TAG_REPLACEMENT_REASON.WRONG_TAG_APPLIED', 'EAR_TAG_REPLACEMENT_REASON.ANIMAL_DIED_BEFORE_TAGGING', 'EAR_TAG_REPLACEMENT_REASON.OTHER', '] as const');
CREATE TYPE IF NOT EXISTS ear_tag_replacement_status AS ENUM ('[
	EAR_TAG_REPLACEMENT_STATUS.PENDING', 'EAR_TAG_REPLACEMENT_STATUS.APPROVED', 'EAR_TAG_REPLACEMENT_STATUS.REJECTED', 'EAR_TAG_REPLACEMENT_STATUS.COMPLETED', 'EAR_TAG_REPLACEMENT_STATUS.CANCELLED', '] as const');
CREATE TYPE IF NOT EXISTS ear_tag_status AS ENUM ('[
	EAR_TAG_STATUS.NEW', 'EAR_TAG_STATUS.AVAILABLE', 'EAR_TAG_STATUS.ORDERED', 'EAR_TAG_STATUS.COLLECTED', 'EAR_TAG_STATUS.DELIVERED', 'EAR_TAG_STATUS.APPLIED', 'EAR_TAG_STATUS.CANCELLED', 'EAR_TAG_STATUS.WITHDRAWN', 'EAR_TAG_STATUS.LOST', 'EAR_TAG_STATUS.DESTROYED', '] as const');
CREATE TYPE IF NOT EXISTS eartag_transition_status AS ENUM ('[
	EARTAG_TRANSITION_STATUS.DELIVERED', 'EARTAG_TRANSITION_STATUS.COMPLETED', '] as const');
CREATE TYPE IF NOT EXISTS email_status AS ENUM ('[
	EMAIL_STATUS.SENT', 'EMAIL_STATUS.QUEUED', 'EMAIL_STATUS.FAILED', '] as const');
CREATE TYPE IF NOT EXISTS entity_type AS ENUM ('[
	ENTITY_TYPE.FARM', 'ENTITY_TYPE.SUBJECT', 'ENTITY_TYPE.FARM_SUBJECT', '] as const');
CREATE TYPE IF NOT EXISTS environment AS ENUM ('[
  ENVIRONMENT.DEV', 'ENVIRONMENT.PRODUCTION', 'ENVIRONMENT.TEST', 'ENVIRONMENT.STAGING', '] as const');
CREATE TYPE IF NOT EXISTS event_source AS ENUM ('[
	EVENT_SOURCE.API', 'EVENT_SOURCE.MOBILE', 'EVENT_SOURCE.SYNC', 'EVENT_SOURCE.SYSTEM', 'EVENT_SOURCE.IMPORT', 'EVENT_SOURCE.WEBHOOK', '] as const');
CREATE TYPE IF NOT EXISTS farm_read_roles AS ENUM ('[
    FARM_READ_ROLE.FARMER', 'FARM_READ_ROLE.SLAUGHTERHOUSE_OP', 'FARM_READ_ROLE.MARKET_OP', '] as const');
CREATE TYPE IF NOT EXISTS farm_type AS ENUM ('[
	FARM_TYPE.FARM', 'FARM_TYPE.SLAUGHTERHOUSE', 'FARM_TYPE.LIVESTOCK_MARKET', 'FARM_TYPE.PASTURE_MOUNTAIN', 'FARM_TYPE.PASTURE_VILLAGE', 'FARM_TYPE.BIP', 'FARM_TYPE.TRADER_YARD', 'FARM_TYPE.QUARANTINE', 'FARM_TYPE.OTHER', '] as const');
CREATE TYPE IF NOT EXISTS holding_type AS ENUM ('[
	HOLDING_TYPE.FARM', 'HOLDING_TYPE.SUBJECT', 'HOLDING_TYPE.ADDRESS', '] as const');
CREATE TYPE IF NOT EXISTS language AS ENUM ('[LANGUAGE.MK', 'LANGUAGE.EN] as const');
CREATE TYPE IF NOT EXISTS module_type AS ENUM ('[
  MODULE_TYPE.CORE', 'MODULE_TYPE.FEATURE', 'MODULE_TYPE.INTEGRATION', 'MODULE_TYPE.REPORT', 'MODULE_TYPE.ADMIN', '] as const');
CREATE TYPE IF NOT EXISTS movement_type AS ENUM ('[
	MOVEMENT_TYPE.SALE', 'MOVEMENT_TYPE.PURCHASE', 'MOVEMENT_TYPE.MARKET_SALE', 'MOVEMENT_TYPE.MARKET_PURCHASE', 'MOVEMENT_TYPE.TRANSFER', 'MOVEMENT_TYPE.BIRTH_REGISTRATION', 'MOVEMENT_TYPE.DEATH', 'MOVEMENT_TYPE.HOME_SLAUGHTER', 'MOVEMENT_TYPE.SLAUGHTERHOUSE', 'MOVEMENT_TYPE.PASTURE_DEPARTURE', 'MOVEMENT_TYPE.PASTURE_RETURN', 'MOVEMENT_TYPE.IMPORT', 'MOVEMENT_TYPE.EXPORT', 'MOVEMENT_TYPE.ALPINE_DEPARTURE', 'MOVEMENT_TYPE.ALPINE_RETURN', 'MOVEMENT_TYPE.CORRECTION', '] as const');
CREATE TYPE IF NOT EXISTS notification_category AS ENUM ('[
	NOTIFICATION_CATEGORY.EAR_TAG_EXPIRATION', 'NOTIFICATION_CATEGORY.EAR_TAG_LOW_STOCK', 'NOTIFICATION_CATEGORY.EAR_TAG_ALLOCATION', 'NOTIFICATION_CATEGORY.EAR_TAG_REPLACEMENT_REQUEST', 'NOTIFICATION_CATEGORY.EAR_TAG_REPLACEMENT_APPROVED', 'NOTIFICATION_CATEGORY.BIRTH_TAGGING_DEADLINE', 'NOTIFICATION_CATEGORY.ANIMAL_MOVEMENT_REQUEST', 'NOTIFICATION_CATEGORY.ANIMAL_MOVEMENT_VERIFICATION', 'NOTIFICATION_CATEGORY.ANIMAL_HEALTH_ALERT', 'NOTIFICATION_CATEGORY.FARM_REGISTRATION_PENDING', 'NOTIFICATION_CATEGORY.FARM_VERIFICATION_REQUIRED', 'NOTIFICATION_CATEGORY.FARM_APPROVED', 'NOTIFICATION_CATEGORY.FARM_REJECTED', 'NOTIFICATION_CATEGORY.SYSTEM_MAINTENANCE', 'NOTIFICATION_CATEGORY.SYSTEM_ERROR', 'NOTIFICATION_CATEGORY.SYSTEM_UPDATE', 'NOTIFICATION_CATEGORY.USER_INVITE', 'NOTIFICATION_CATEGORY.USER_PASSWORD_RESET', 'NOTIFICATION_CATEGORY.USER_ROLE_CHANGED', 'NOTIFICATION_CATEGORY.USER_LOGIN_ALERT', 'NOTIFICATION_CATEGORY.INSPECTION_DUE', 'NOTIFICATION_CATEGORY.INSPECTION_OVERDUE', 'NOTIFICATION_CATEGORY.QUARANTINE_ALERT', 'NOTIFICATION_CATEGORY.DISEASE_OUTBREAK', 'NOTIFICATION_CATEGORY.REPORT_GENERATED', 'NOTIFICATION_CATEGORY.REPORT_FAILED', 'NOTIFICATION_CATEGORY.DATA_SYNC_COMPLETE', 'NOTIFICATION_CATEGORY.DATA_SYNC_FAILED', '] as const');
CREATE TYPE IF NOT EXISTS notification_priority AS ENUM ('[
	NOTIFICATION_PRIORITY.LOW', 'NOTIFICATION_PRIORITY.NORMAL', 'NOTIFICATION_PRIORITY.HIGH', 'NOTIFICATION_PRIORITY.URGENT', 'NOTIFICATION_PRIORITY.CRITICAL', '] as const');
CREATE TYPE IF NOT EXISTS notification_status AS ENUM ('[
	NOTIFICATION_STATUS.PENDING', 'NOTIFICATION_STATUS.SENT', 'NOTIFICATION_STATUS.DELIVERED', 'NOTIFICATION_STATUS.FAILED', 'NOTIFICATION_STATUS.CANCELLED', '] as const');
CREATE TYPE IF NOT EXISTS notification_type AS ENUM ('[
	NOTIFICATION_TYPE.EMAIL', 'NOTIFICATION_TYPE.SMS', 'NOTIFICATION_TYPE.PUSH', 'NOTIFICATION_TYPE.IN_APP', 'NOTIFICATION_TYPE.WEBHOOK', '] as const');
CREATE TYPE IF NOT EXISTS order_status AS ENUM ('[
	ORDER_STATUS.PENDING', 'ORDER_STATUS.COLLECTED', 'ORDER_STATUS.DELIVERED', 'ORDER_STATUS.PARTIALLY_DELIVERED', 'ORDER_STATUS.CANCELLED', 'ORDER_STATUS.COMPLETED', '] as const');
CREATE TYPE IF NOT EXISTS org_read_roles AS ENUM ('[
    ORG_READ_ROLE.VETERINARIAN', 'ORG_READ_ROLE.TECHNICIAN', '] as const');
CREATE TYPE IF NOT EXISTS org_type AS ENUM ('[
  ORG_TYPE.VD', 'ORG_TYPE.VET_CLINIC', 'ORG_TYPE.SLAUGHTERHOUSE', 'ORG_TYPE.LIVESTOCK_MARKET', 'ORG_TYPE.FARM_ASSOCIATION', 'ORG_TYPE.GOVERNMENT', 'ORG_TYPE.OTHER', '] as const');
CREATE TYPE IF NOT EXISTS parent_type AS ENUM ('[
  PARENT_TYPE.MOTHER', 'PARENT_TYPE.FATHER', '] as const');
CREATE TYPE IF NOT EXISTS pasture_type AS ENUM ('[
	PASTURE_TYPE.MOUNTAIN', 'PASTURE_TYPE.VILLAGE', '] as const');
CREATE TYPE IF NOT EXISTS role_priority AS ENUM ('[
  ROLE_PRIORITY.NORMAL', 'ROLE_PRIORITY.HIGH', 'ROLE_PRIORITY.CRITICAL', 'ROLE_PRIORITY.LOW', '] as const');
CREATE TYPE IF NOT EXISTS severity AS ENUM ('[
  SEVERITY.ERROR', 'SEVERITY.WARNING', 'SEVERITY.INFO', 'SEVERITY.DEBUG', '] as const');
CREATE TYPE IF NOT EXISTS sex AS ENUM ('[SEX.MALE', 'SEX.FEMALE] as const');
CREATE TYPE IF NOT EXISTS sort_animal_by AS ENUM ('[
	SORT_ANIMAL_BY.BIRTH_DATE', 'SORT_ANIMAL_BY.CREATED_AT', 'SORT_ANIMAL_BY.EAR_TAG_NUMBER', '] as const');
CREATE TYPE IF NOT EXISTS sort_by_eartag AS ENUM ('[
  SORT_BY_EARTAG.CREATED_AT', 'SORT_BY_EARTAG.APPLIED_DATE', 'SORT_BY_EARTAG.MANUFACTURE_DATE', '] as const');
CREATE TYPE IF NOT EXISTS sort_by_farm AS ENUM ('[
  SORT_BY_FARM.NAME', 'SORT_BY_FARM.FARM_ID', 'SORT_BY_FARM.CREATED_AT', '] as const');
CREATE TYPE IF NOT EXISTS sort_by_movement AS ENUM ('[
  SORT_BY_MOVEMENT.MOVEMENT_DATE', 'SORT_BY_MOVEMENT.CREATED_AT', '] as const');
CREATE TYPE IF NOT EXISTS sort_by_user AS ENUM ('[
  SORT_BY_USER.USERNAME', 'SORT_BY_USER.CREATED_AT', 'SORT_BY_USER.LAST_LOGIN_AT', '] as const');
CREATE TYPE IF NOT EXISTS sort_order AS ENUM ('[
	SORT_ORDER.ASC', 'SORT_ORDER.DESC', '] as const');
CREATE TYPE IF NOT EXISTS state_code AS ENUM ('[
	STATE_CODE.MK', '] as const');
CREATE TYPE IF NOT EXISTS subject_role AS ENUM ('[
	SUBJECT_ROLE.OWNER', 'SUBJECT_ROLE.KEEPER', 'SUBJECT_ROLE.VETERINARIAN', 'SUBJECT_ROLE.TRADER', 'SUBJECT_ROLE.SLAUGHTERHOUSE_OP', 'SUBJECT_ROLE.MARKET_OP', 'SUBJECT_ROLE.TECHNICIAN', 'SUBJECT_ROLE.GUARDIAN', '] as const');
CREATE TYPE IF NOT EXISTS sync_error_type AS ENUM ('[
  SYNC_ERROR_TYPE.PARSE_ERROR', 'SYNC_ERROR_TYPE.VALIDATION_ERROR', 'SYNC_ERROR_TYPE.NETWORK_ERROR', 'SYNC_ERROR_TYPE.DUPLICATE', 'SYNC_ERROR_TYPE.UNKNOWN', '] as const');
CREATE TYPE IF NOT EXISTS tag_category AS ENUM ('[
  TAG_CATEGORY.ELECTRONIC', 'TAG_CATEGORY.VISUAL', 'TAG_CATEGORY.BOTH', '] as const');
CREATE TYPE IF NOT EXISTS user_role AS ENUM ('[
  USER_ROLE.SUPER_ADMIN', 'USER_ROLE.VD_ADMIN', 'USER_ROLE.VD_STAFF', 'USER_ROLE.VETERINARIAN', 'USER_ROLE.TECHNICIAN', 'USER_ROLE.SLAUGHTERHOUSE_OP', 'USER_ROLE.MARKET_OP', 'USER_ROLE.FARMER', '] as const');
CREATE TYPE IF NOT EXISTS user_status AS ENUM ('[
	USER_STATUS.ACTIVE', 'USER_STATUS.INACTIVE', 'USER_STATUS.BLOCKED', 'USER_STATUS.PENDING_VERIFICATION', '] as const');
CREATE TYPE IF NOT EXISTS verification_status AS ENUM ('[
	VERIFICATION_STATUS.DRAFT', 'VERIFICATION_STATUS.PENDING_VD_APPROVAL', 'VERIFICATION_STATUS.APPROVED', 'VERIFICATION_STATUS.REJECTED', 'VERIFICATION_STATUS.ARCHIVED', '] as const');
CREATE TYPE IF NOT EXISTS weighing_type AS ENUM ('[WEIGHING_TYPE.LIVE_WEIGHT', 'WEIGHING_TYPE.WARM_HALVES] as const');
CREATE TYPE IF NOT EXISTS write_roles AS ENUM ('[
    WRITE_ROLE.SUPER_ADMIN', 'WRITE_ROLE.VD_ADMIN', 'WRITE_ROLE.VD_STAFF', 'WRITE_ROLE.VETERINARIAN', '] as const');

-- Swap varchar columns to pgEnum types

ALTER TABLE animals ALTER COLUMN state_code TYPE state_code USING state_code::state_code;
ALTER TABLE animals ALTER COLUMN sex TYPE sex USING sex::sex;
ALTER TABLE animals ALTER COLUMN birth_type TYPE birth_type USING birth_type::birth_type;
ALTER TABLE animals ALTER COLUMN status TYPE animal_status USING status::animal_status;
ALTER TABLE animals ALTER COLUMN parent_type TYPE parent_type USING parent_type::parent_type;
ALTER TABLE birth_notifications ALTER COLUMN source TYPE event_source USING source::event_source;
ALTER TABLE birth_notifications ALTER COLUMN status TYPE birth_notification_status USING status::birth_notification_status;
ALTER TABLE movements ALTER COLUMN type TYPE movement_type USING type::movement_type;
ALTER TABLE movements ALTER COLUMN death_cause TYPE death_cause USING death_cause::death_cause;
ALTER TABLE pasture_declarations ALTER COLUMN pasture_type TYPE pasture_type USING pasture_type::pasture_type;
ALTER TABLE slaughter_records ALTER COLUMN mass_type TYPE slaughter_mass_type USING mass_type::slaughter_mass_type;
ALTER TABLE ear_tags ALTER COLUMN state_code TYPE state_code USING state_code::state_code;
ALTER TABLE ear_tags ALTER COLUMN status TYPE ear_tag_status USING status::ear_tag_status;
ALTER TABLE ear_tag_orders ALTER COLUMN status TYPE ear_tag_order_status USING status::ear_tag_order_status;
ALTER TABLE ear_tag_replacements ALTER COLUMN reason TYPE ear_tag_replacement_reason USING reason::ear_tag_replacement_reason;
ALTER TABLE ear_tag_replacements ALTER COLUMN status TYPE ear_tag_replacement_status USING status::ear_tag_replacement_status;
ALTER TABLE ear_tag_allocations ALTER COLUMN distribution_method TYPE distribution_method USING distribution_method::distribution_method;
ALTER TABLE ear_tag_allocations ALTER COLUMN status TYPE allocation_status USING status::allocation_status;
ALTER TABLE ear_tag_types ALTER COLUMN category TYPE tag_category USING category::tag_category;
ALTER TABLE farms ALTER COLUMN type TYPE farm_type USING type::farm_type;
ALTER TABLE farms ALTER COLUMN verification_status TYPE verification_status USING verification_status::verification_status;
ALTER TABLE farms ALTER COLUMN data_source TYPE data_source USING data_source::data_source;
ALTER TABLE farm_subjects ALTER COLUMN role TYPE subject_role USING role::subject_role;
ALTER TABLE sync_errors ALTER COLUMN error_type TYPE sync_error_type USING error_type::sync_error_type;
ALTER TABLE notifications ALTER COLUMN type TYPE notification_type USING type::notification_type;
ALTER TABLE notifications ALTER COLUMN category TYPE notification_category USING category::notification_category;
ALTER TABLE notifications ALTER COLUMN priority TYPE notification_priority USING priority::notification_priority;
ALTER TABLE notifications ALTER COLUMN status TYPE notification_status USING status::notification_status;
ALTER TABLE notifications ALTER COLUMN source TYPE event_source USING source::event_source;
ALTER TABLE notification_templates ALTER COLUMN type TYPE notification_type USING type::notification_type;
ALTER TABLE notification_templates ALTER COLUMN category TYPE notification_category USING category::notification_category;
ALTER TABLE notification_templates ALTER COLUMN priority TYPE notification_priority USING priority::notification_priority;
ALTER TABLE notification_preferences ALTER COLUMN category TYPE notification_category USING category::notification_category;
ALTER TABLE audit_log ALTER COLUMN action TYPE audit_action USING action::audit_action;
ALTER TABLE audit_log ALTER COLUMN source TYPE event_source USING source::event_source;
ALTER TABLE organizations ALTER COLUMN org_type TYPE org_type USING org_type::org_type;
ALTER TABLE modules ALTER COLUMN type TYPE module_type USING type::module_type;
ALTER TABLE modules ALTER COLUMN severity TYPE severity USING severity::severity;
