// ── Check Digit & ID Generation Utilities ──
// Legacy algorithms preserved for backward compatibility
// Source: TPC_PDA_v1_2.pdf §2.3, FS - eartags_MK(v1.0).pdf p6

import { z } from "zod";

// ============================================================================
// EAR TAG CHECK DIGIT
// Source: FS - eartags_MK(v1.0).pdf, page 6
// "Check digit is automatically generated by this formula:
//   Check digit = MOD 10 of SUM(3*dig1 + 5*dig2 + 7*dig3 + 11*dig4
//                              + 13*dig5 + 17*dig6 + 19*dig7)"
// ============================================================================

// ============================================================================
// PROVIDER MODEL (ADR-0030 §B) — algorithms are providers, not constants.
// The active jurisdiction selects a CheckDigitProvider; MK is the default.
// Domain exporters (e.g. generateTakeoverFile, WO-001) MUST call the active
// provider, never a private formula.
// ============================================================================

export interface CheckDigitProvider {
  readonly name: string;
  readonly weights: readonly number[];
  readonly modulus: number;
  readonly basePattern: RegExp;
  readonly fullPattern: RegExp;
  calculate(firstDigits: string): number;
  validate(tag: string): boolean;
}

function makeCheckDigitProvider(opts: {
  name: string;
  weights: readonly number[];
  baseLength: number;
  modulus?: number;
}): CheckDigitProvider {
  const modulus = opts.modulus ?? 10;
  const basePattern = new RegExp(`^\\d{${opts.baseLength}}$`);
  const fullPattern = new RegExp(`^\\d{${opts.baseLength + 1}}$`);
  return {
    name: opts.name,
    weights: opts.weights,
    modulus,
    basePattern,
    fullPattern,
    calculate(firstDigits: string): number {
      if (!basePattern.test(firstDigits)) {
        throw new Error(`First ${opts.baseLength} digits must be a ${opts.baseLength}-digit number`);
      }
      const sum = firstDigits
        .split("")
        .map(Number)
        .reduce((acc, digit, i) => acc + opts.weights[i]! * digit, 0);
      return sum % modulus;
    },
    validate(tag: string): boolean {
      if (!fullPattern.test(tag)) return false;
      const digits = tag.split("").map(Number);
      const sum = digits
        .slice(0, opts.baseLength)
        .reduce((acc, d, i) => acc + opts.weights[i]! * d, 0);
      return digits[opts.baseLength]! === sum % modulus;
    },
  };
}

// MK (Macedonian) default — FS - eartags_MK(v1.0).pdf p6
export const MK_EAR_TAG_CHECK_DIGIT_PROVIDER = makeCheckDigitProvider({
  name: "MK",
  weights: [3, 5, 7, 11, 13, 17, 19],
  baseLength: 7,
});

// MK Farm ID — TPC_PDA_v1_2.pdf §2.3 (9-digit Farm ID)
export const MK_FARM_ID_CHECK_DIGIT_PROVIDER = makeCheckDigitProvider({
  name: "MK_FARM",
  weights: [7, 3, 1, 9, 5, 11, 13, 17],
  baseLength: 8,
});

export const CHECK_DIGIT_PROVIDERS: Readonly<Record<string, CheckDigitProvider>> = {
  MK: MK_EAR_TAG_CHECK_DIGIT_PROVIDER,
  MK_FARM: MK_FARM_ID_CHECK_DIGIT_PROVIDER,
};

export function getCheckDigitProvider(name = "MK"): CheckDigitProvider {
  const provider = CHECK_DIGIT_PROVIDERS[name];
  if (!provider) throw new Error(`Unknown check-digit provider: ${name}`);
  return provider;
}

// ── Backward-compatible exports (delegate to the MK ear-tag provider) ──
const EAR_TAG_WEIGHTS = MK_EAR_TAG_CHECK_DIGIT_PROVIDER.weights;

export function calculateEarTagCheckDigit(first7Digits: string): number {
  return MK_EAR_TAG_CHECK_DIGIT_PROVIDER.calculate(first7Digits);
}

export function validateEarTagCheckDigit(tag: string): boolean {
  return MK_EAR_TAG_CHECK_DIGIT_PROVIDER.validate(tag);
}

export const earTagSchema = z
  .string()
  .regex(/^\d{8}$/, "Ear tag must be exactly 8 digits")
  .refine(validateEarTagCheckDigit, "Ear tag check digit is invalid");

// ============================================================================
// FARM ID CHECK DIGIT
// Source: TPC_PDA_v1_2.pdf §2.3
// Legacy: PDA_DEVICE_ID * 100000 + counter → replaced with centralized utility
// New: 9-digit Farm ID with check digit
// ============================================================================

export function calculateFarmIdCheckDigit(first8Digits: string): number {
  return MK_FARM_ID_CHECK_DIGIT_PROVIDER.calculate(first8Digits);
}

export function generateFarmId(sequence: number): string {
  const padded = String(sequence).padStart(8, "0");
  const checkDigit = calculateFarmIdCheckDigit(padded);
  return padded + checkDigit;
}

export const farmIdSchema = z
  .string()
  .regex(/^\d{9}$/, "Farm ID must be exactly 9 digits")
  .refine(
    (id) => {
      const checkDigit = calculateFarmIdCheckDigit(id.slice(0, 8));
      return parseInt(id[8]!, 10) === checkDigit;
    },
    "Farm ID check digit is invalid"
  );

// ============================================================================
// UUID & ID GENERATION
// ============================================================================

/** Generate a UUID v4 (for new records) */
export function generateId(): string {
  return crypto.randomUUID();
}

/** Legacy ID sequence simulator (only for migration compatibility) */
const sequenceCounters = new Map<string, number>();

export function nextLegacySequence(name: string): number {
  const current = sequenceCounters.get(name) ?? 0;
  sequenceCounters.set(name, current + 1);
  return current + 1;
}

// ============================================================================
// CATTLE PASSPORT NUMBER
// ============================================================================

/** Generate a cattle passport number: MK-YYYY-XXXXX */
export function generatePassportNumber(year: number, sequence: number): string {
  return `MK-${year}-${String(sequence).padStart(5, "0")}`;
}

// ============================================================================
// DATE HELPERS
// ============================================================================

/** Difference in days between two dates */
export function daysBetween(a: Date, b: Date): number {
  return Math.floor(
    (b.getTime() - a.getTime()) / (1000 * 60 * 60 * 24)
  );
}

/** Difference in months between two dates */
export function monthsBetween(a: Date, b: Date): number {
  return (
    (b.getFullYear() - a.getFullYear()) * 12 +
    (b.getMonth() - a.getMonth())
  );
}

/** Calculate tagging deadline: 20 days after birth (legacy rule) */
export function calculateTaggingDeadline(birthDate: Date): Date {
  const deadline = new Date(birthDate);
  deadline.setDate(deadline.getDate() + 20);
  return deadline;
}

/** Calculate order interval: 120 days minimum (legacy rule) */
export function isOrderAllowed(lastOrderDate: Date | null): boolean {
  if (!lastOrderDate) return true;
  return daysBetween(lastOrderDate, new Date()) >= 120;
}

// ============================================================================
// VALIDATION HELPERS
// ============================================================================

/** Zod refinement: date cannot be in the future */
export const notInFuture = z.date().refine(
  (d) => d <= new Date(),
  "Date cannot be in the future"
);

/** Zod refinement: date must be in the past */
export const notBeforeBirth = (birthDate: Date) =>
  z.date().refine(
    (d) => d >= birthDate,
    "Date must be after birth date"
  );

/**
 * WO-118 — ISO 11784/11785 ear-tag format validation (R2, USDA APHIS ADT 9 CFR 86).
 * ISO_11784_15: exactly 15 digits, prefixed by the jurisdiction ISO 3166-1 numeric
 * country code (e.g. "840" = USA). MK_8: 8 digits with the MK weighted check digit.
 * Takes primitives (not the RuleSet) to avoid a validators->system dependency.
 */
export function validateEarTagFormat(tagNumber: string, format: string, prefix: string): boolean {
  if (format === "ISO_11784_15") {
    return /^\d{15}$/.test(tagNumber) && tagNumber.startsWith(prefix);
  }
  if (format === "MK_8") {
    return getCheckDigitProvider().validate(tagNumber);
  }
  return false;
}
