// ── Check Digit & ID Generation Utilities ──
// Legacy algorithms preserved for backward compatibility
// Source: TPC_PDA_v1_2.pdf §2.3, FS - eartags_MK(v1.0).pdf p6

import { z } from "zod";

// ============================================================================
// EAR TAG CHECK DIGIT
// Source: FS - eartags_MK(v1.0).pdf, page 6
// "Check digit is automatically generated by this formula:
//   Check digit = MOD 10 of SUM(3*dig1 + 5*dig2 + 7*dig3 + 11*dig4
//                              + 13*dig5 + 17*dig6 + 19*dig7)"
// ============================================================================

const EAR_TAG_WEIGHTS = [3, 5, 7, 11, 13, 17, 19];

export function calculateEarTagCheckDigit(first7Digits: string): number {
  if (!/^\d{7}$/.test(first7Digits)) {
    throw new Error("First 7 digits must be a 7-digit number");
  }
  const sum = first7Digits
    .split("")
    .map(Number)
    .reduce((acc, digit, i) => acc + EAR_TAG_WEIGHTS[i]! * digit, 0);
  return sum % 10;
}

export function validateEarTagCheckDigit(tag: string): boolean {
  if (!/^\d{8}$/.test(tag)) return false;
  const digits = tag.split("").map(Number);
  const sum = digits
    .slice(0, 7)
    .reduce((acc, d, i) => acc + EAR_TAG_WEIGHTS[i]! * d, 0);
  return digits[7] === sum % 10;
}

export const earTagSchema = z
  .string()
  .regex(/^\d{8}$/, "Ear tag must be exactly 8 digits")
  .refine(validateEarTagCheckDigit, "Ear tag check digit is invalid");

// ============================================================================
// FARM ID CHECK DIGIT
// Source: TPC_PDA_v1_2.pdf §2.3
// Legacy: PDA_DEVICE_ID * 100000 + counter → replaced with centralized utility
// New: 9-digit Farm ID with check digit
// ============================================================================

const FARM_ID_WEIGHTS = [7, 3, 1, 9, 5, 11, 13, 17];

export function calculateFarmIdCheckDigit(first8Digits: string): number {
  if (!/^\d{8}$/.test(first8Digits)) {
    throw new Error("First 8 digits must be an 8-digit number");
  }
  const sum = first8Digits
    .split("")
    .map(Number)
    .reduce((acc, digit, i) => acc + FARM_ID_WEIGHTS[i]! * digit, 0);
  return sum % 10;
}

export function generateFarmId(sequence: number): string {
  const padded = String(sequence).padStart(8, "0");
  const checkDigit = calculateFarmIdCheckDigit(padded);
  return padded + checkDigit;
}

export const farmIdSchema = z
  .string()
  .regex(/^\d{9}$/, "Farm ID must be exactly 9 digits")
  .refine(
    (id) => {
      const checkDigit = calculateFarmIdCheckDigit(id.slice(0, 8));
      return parseInt(id[8]!, 10) === checkDigit;
    },
    "Farm ID check digit is invalid"
  );

// ============================================================================
// UUID & ID GENERATION
// ============================================================================

/** Generate a UUID v4 (for new records) */
export function generateId(): string {
  return crypto.randomUUID();
}

/** Legacy ID sequence simulator (only for migration compatibility) */
const sequenceCounters = new Map<string, number>();

export function nextLegacySequence(name: string): number {
  const current = sequenceCounters.get(name) ?? 0;
  sequenceCounters.set(name, current + 1);
  return current + 1;
}

// ============================================================================
// CATTLE PASSPORT NUMBER
// ============================================================================

/** Generate a cattle passport number: MK-YYYY-XXXXX */
export function generatePassportNumber(year: number, sequence: number): string {
  return `MK-${year}-${String(sequence).padStart(5, "0")}`;
}

// ============================================================================
// DATE HELPERS
// ============================================================================

/** Difference in days between two dates */
export function daysBetween(a: Date, b: Date): number {
  return Math.floor(
    (b.getTime() - a.getTime()) / (1000 * 60 * 60 * 24)
  );
}

/** Difference in months between two dates */
export function monthsBetween(a: Date, b: Date): number {
  return (
    (b.getFullYear() - a.getFullYear()) * 12 +
    (b.getMonth() - a.getMonth())
  );
}

/** Calculate tagging deadline: 20 days after birth (legacy rule) */
export function calculateTaggingDeadline(birthDate: Date): Date {
  const deadline = new Date(birthDate);
  deadline.setDate(deadline.getDate() + 20);
  return deadline;
}

/** Calculate order interval: 120 days minimum (legacy rule) */
export function isOrderAllowed(lastOrderDate: Date | null): boolean {
  if (!lastOrderDate) return true;
  return daysBetween(lastOrderDate, new Date()) >= 120;
}

// ============================================================================
// VALIDATION HELPERS
// ============================================================================

/** Zod refinement: date cannot be in the future */
export const notInFuture = z.date().refine(
  (d) => d <= new Date(),
  "Date cannot be in the future"
);

/** Zod refinement: date must be in the past */
export const notBeforeBirth = (birthDate: Date) =>
  z.date().refine(
    (d) => d >= birthDate,
    "Date must be after birth date"
  );
