import { createEnumValues } from "./_brand.js"

export const ALLOCATION_STATUS = {
  PENDING: "PENDING",
  PARTIALLY_FULFILLED: "PARTIALLY_FULFILLED",
  FULFILLED: "FULFILLED",
  CANCELLED: "CANCELLED",
} as const;

export const ALLOCATION_STATUS_VALUES = createEnumValues([
  ALLOCATION_STATUS.PENDING,
  ALLOCATION_STATUS.PARTIALLY_FULFILLED,
  ALLOCATION_STATUS.FULFILLED,
  ALLOCATION_STATUS.CANCELLED,
] as const);
