import { createEnumValues } from "./_brand"

export const ARCHIVE_DOCUMENT_TYPE = {
	PASSPORT: "passport",
	CENSUS_FORM: "census_form",
	TAGGING_RECEIPT: "tagging_receipt",
	ORDER_FORM: "order_form",
	INSPECTION_FORM: "inspection_form",
	SLAUGHTER_LIST: "slaughter_list",
	CORRESPONDENCE: "correspondence",
	OTHER: "other",
} as const;

export const ARCHIVE_DOCUMENT_TYPE_VALUES = createEnumValues([
	ARCHIVE_DOCUMENT_TYPE.PASSPORT,
	ARCHIVE_DOCUMENT_TYPE.CENSUS_FORM,
	ARCHIVE_DOCUMENT_TYPE.TAGGING_RECEIPT,
	ARCHIVE_DOCUMENT_TYPE.ORDER_FORM,
	ARCHIVE_DOCUMENT_TYPE.INSPECTION_FORM,
	ARCHIVE_DOCUMENT_TYPE.SLAUGHTER_LIST,
	ARCHIVE_DOCUMENT_TYPE.CORRESPONDENCE,
	ARCHIVE_DOCUMENT_TYPE.OTHER,
] as const);
