import { createEnumValues } from "./_brand.js";

/**
 * Death Cause — why did the animal leave the Symbolic order?
 */
export const DEATH_CAUSE = {
	DEATH_REGISTERED: "DEATH_REGISTERED",
	DEATH_UNREGISTERED: "DEATH_UNREGISTERED",
	DEATH_UNREGISTERED_IMPORT: "DEATH_UNREGISTERED_IMPORT",
	STILLBORN: "STILLBORN",
	DEATH_AFTER_BIRTH: "DEATH_AFTER_BIRTH",
} as const;

export const DEATH_CAUSE_VALUES = createEnumValues([
	DEATH_CAUSE.DEATH_REGISTERED,
	DEATH_CAUSE.DEATH_UNREGISTERED,
	DEATH_CAUSE.DEATH_UNREGISTERED_IMPORT,
	DEATH_CAUSE.STILLBORN,
	DEATH_CAUSE.DEATH_AFTER_BIRTH,
] as const);
