import { createEnumValues } from "./_brand.js"

export const EAR_TAG_REPLACEMENT_REASON = {
	LOST: "lost",
	DAMAGED: "damaged",
	DEFECTIVE: "defective",
	ILLEGIBLE: "illegible",
	WRONG_TAG_APPLIED: "wrong_tag_applied",
	ANIMAL_DIED_BEFORE_TAGGING: "animal_died_before_tagging",
	OTHER: "other",
} as const;

export const EAR_TAG_REPLACEMENT_REASON_VALUES = createEnumValues([
	EAR_TAG_REPLACEMENT_REASON.LOST,
	EAR_TAG_REPLACEMENT_REASON.DAMAGED,
	EAR_TAG_REPLACEMENT_REASON.DEFECTIVE,
	EAR_TAG_REPLACEMENT_REASON.ILLEGIBLE,
	EAR_TAG_REPLACEMENT_REASON.WRONG_TAG_APPLIED,
	EAR_TAG_REPLACEMENT_REASON.ANIMAL_DIED_BEFORE_TAGGING,
	EAR_TAG_REPLACEMENT_REASON.OTHER,
] as const);
