import { createEnumValues } from "./_brand.js"

export const MOVEMENT_TYPE = {
	SALE: "sale",
	PURCHASE: "purchase",
	MARKET_SALE: "market_sale",
	MARKET_PURCHASE: "market_purchase",
	TRANSFER: "transfer",
	BIRTH_REGISTRATION: "birth_registration",
	DEATH: "death",
	HOME_SLAUGHTER: "home_slaughter",
	SLAUGHTERHOUSE: "slaughterhouse",
	PASTURE_DEPARTURE: "pasture_departure",
	PASTURE_RETURN: "pasture_return",
	IMPORT: "import",
	EXPORT: "export",
	ALPINE_DEPARTURE: "alpine_departure",
	ALPINE_RETURN: "alpine_return",
	CORRECTION: "correction",
} as const;

export const MOVEMENT_TYPE_VALUES = createEnumValues([
	MOVEMENT_TYPE.SALE,
	MOVEMENT_TYPE.PURCHASE,
	MOVEMENT_TYPE.MARKET_SALE,
	MOVEMENT_TYPE.MARKET_PURCHASE,
	MOVEMENT_TYPE.TRANSFER,
	MOVEMENT_TYPE.BIRTH_REGISTRATION,
	MOVEMENT_TYPE.DEATH,
	MOVEMENT_TYPE.HOME_SLAUGHTER,
	MOVEMENT_TYPE.SLAUGHTERHOUSE,
	MOVEMENT_TYPE.PASTURE_DEPARTURE,
	MOVEMENT_TYPE.PASTURE_RETURN,
	MOVEMENT_TYPE.IMPORT,
	MOVEMENT_TYPE.EXPORT,
	MOVEMENT_TYPE.ALPINE_DEPARTURE,
	MOVEMENT_TYPE.ALPINE_RETURN,
	MOVEMENT_TYPE.CORRECTION,
] as const);
