import { createEnumValues } from "./_brand.js"

export const NOTIFICATION_CATEGORY = {
	// Ear tag notifications
	EAR_TAG_EXPIRATION: "ear_tag_expiration",
	EAR_TAG_LOW_STOCK: "ear_tag_low_stock",
	EAR_TAG_ALLOCATION: "ear_tag_allocation",
	EAR_TAG_REPLACEMENT_REQUEST: "ear_tag_replacement_request",
	EAR_TAG_REPLACEMENT_APPROVED: "ear_tag_replacement_approved",

	// Animal notifications
	BIRTH_TAGGING_DEADLINE: "birth_tagging_deadline",
	ANIMAL_MOVEMENT_REQUEST: "animal_movement_request",
	ANIMAL_MOVEMENT_VERIFICATION: "animal_movement_verification",
	ANIMAL_HEALTH_ALERT: "animal_health_alert",

	// Farm notifications
	FARM_REGISTRATION_PENDING: "farm_registration_pending",
	FARM_VERIFICATION_REQUIRED: "farm_verification_required",
	FARM_APPROVED: "farm_approved",
	FARM_REJECTED: "farm_rejected",

	// System notifications
	SYSTEM_MAINTENANCE: "system_maintenance",
	SYSTEM_ERROR: "system_error",
	SYSTEM_UPDATE: "system_update",

	// User notifications
	USER_INVITE: "user_invite",
	USER_PASSWORD_RESET: "user_password_reset",
	USER_ROLE_CHANGED: "user_role_changed",
	USER_LOGIN_ALERT: "user_login_alert",

	// Regulatory notifications
	INSPECTION_DUE: "inspection_due",
	INSPECTION_OVERDUE: "inspection_overdue",
	QUARANTINE_ALERT: "quarantine_alert",
	DISEASE_OUTBREAK: "disease_outbreak",

	// Reports and analytics
	REPORT_GENERATED: "report_generated",
	REPORT_FAILED: "report_failed",
	DATA_SYNC_COMPLETE: "data_sync_complete",
	DATA_SYNC_FAILED: "data_sync_failed",
} as const;

export const NOTIFICATION_CATEGORY_VALUES = createEnumValues([
	NOTIFICATION_CATEGORY.EAR_TAG_EXPIRATION,
	NOTIFICATION_CATEGORY.EAR_TAG_LOW_STOCK,
	NOTIFICATION_CATEGORY.EAR_TAG_ALLOCATION,
	NOTIFICATION_CATEGORY.EAR_TAG_REPLACEMENT_REQUEST,
	NOTIFICATION_CATEGORY.EAR_TAG_REPLACEMENT_APPROVED,
	NOTIFICATION_CATEGORY.BIRTH_TAGGING_DEADLINE,
	NOTIFICATION_CATEGORY.ANIMAL_MOVEMENT_REQUEST,
	NOTIFICATION_CATEGORY.ANIMAL_MOVEMENT_VERIFICATION,
	NOTIFICATION_CATEGORY.ANIMAL_HEALTH_ALERT,
	NOTIFICATION_CATEGORY.FARM_REGISTRATION_PENDING,
	NOTIFICATION_CATEGORY.FARM_VERIFICATION_REQUIRED,
	NOTIFICATION_CATEGORY.FARM_APPROVED,
	NOTIFICATION_CATEGORY.FARM_REJECTED,
	NOTIFICATION_CATEGORY.SYSTEM_MAINTENANCE,
	NOTIFICATION_CATEGORY.SYSTEM_ERROR,
	NOTIFICATION_CATEGORY.SYSTEM_UPDATE,
	NOTIFICATION_CATEGORY.USER_INVITE,
	NOTIFICATION_CATEGORY.USER_PASSWORD_RESET,
	NOTIFICATION_CATEGORY.USER_ROLE_CHANGED,
	NOTIFICATION_CATEGORY.USER_LOGIN_ALERT,
	NOTIFICATION_CATEGORY.INSPECTION_DUE,
	NOTIFICATION_CATEGORY.INSPECTION_OVERDUE,
	NOTIFICATION_CATEGORY.QUARANTINE_ALERT,
	NOTIFICATION_CATEGORY.DISEASE_OUTBREAK,
	NOTIFICATION_CATEGORY.REPORT_GENERATED,
	NOTIFICATION_CATEGORY.REPORT_FAILED,
	NOTIFICATION_CATEGORY.DATA_SYNC_COMPLETE,
	NOTIFICATION_CATEGORY.DATA_SYNC_FAILED,
] as const);
