import { createEnumValues } from "./_brand.js"

export const ORG_TYPE = {
  VD: "VD",
  VET_CLINIC: "VET_CLINIC",
  SLAUGHTERHOUSE: "SLAUGHTERHOUSE",
  LIVESTOCK_MARKET: "LIVESTOCK_MARKET",
  FARM_ASSOCIATION: "FARM_ASSOCIATION",
  GOVERNMENT: "GOVERNMENT",
  OTHER: "OTHER",
} as const;

export const ORG_TYPE_VALUES = createEnumValues([
  ORG_TYPE.VD,
  ORG_TYPE.VET_CLINIC,
  ORG_TYPE.SLAUGHTERHOUSE,
  ORG_TYPE.LIVESTOCK_MARKET,
  ORG_TYPE.FARM_ASSOCIATION,
  ORG_TYPE.GOVERNMENT,
  ORG_TYPE.OTHER,
] as const);
