import { createEnumValues } from "./_brand.js"

export const SYNC_ERROR_TYPE = {
  PARSE_ERROR: "PARSE_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  DUPLICATE: "DUPLICATE",
  UNKNOWN: "UNKNOWN",
} as const;

export const SYNC_ERROR_TYPE_VALUES = createEnumValues([
  SYNC_ERROR_TYPE.PARSE_ERROR,
  SYNC_ERROR_TYPE.VALIDATION_ERROR,
  SYNC_ERROR_TYPE.NETWORK_ERROR,
  SYNC_ERROR_TYPE.DUPLICATE,
  SYNC_ERROR_TYPE.UNKNOWN,
] as const);
