import { createEnumValues } from "./_brand.js";

export const TRANSMISSION_TYPE = {
	LORAWAN: "LORAWAN",
	SIGFOX: "SIGFOX",
	NB_IOT: "NB_IOT",
	LTE_M: "LTE_M",
	SATELLITE: "SATELLITE",
	BLUETOOTH: "BLUETOOTH",
} as const;

export const TRANSMISSION_TYPE_VALUES = createEnumValues([
	TRANSMISSION_TYPE.LORAWAN,
	TRANSMISSION_TYPE.SIGFOX,
	TRANSMISSION_TYPE.NB_IOT,
	TRANSMISSION_TYPE.LTE_M,
	TRANSMISSION_TYPE.SATELLITE,
	TRANSMISSION_TYPE.BLUETOOTH,
] as const);
