// ── tRPC wire-boundary acceptance suite ──
//
// Exercises EVERY tRPC procedure exposed by `appRouter` (currently 180,
// generated by nestjs-trpc). For each procedure that carries an input
// schema it asserts, with ZERO hand-written literals or enums:
//
//   1. the schema-walker-derived input (buildInput) passes the procedure's
//      own input Zod schema, and the call is ACCEPTED by the wire
//      (resolves — the generated resolver is a PLACEHOLDER that returns a
//      defined envelope, proving the input contract is satisfied end-to-end);
//   2. a corrupted variant of that input is REJECTED (throws TRPCError),
//      proving the input contract is enforced.
//
// The 8 factory-less routers (modules, system-parameters, ched, eudr,
// diseaseZone, holdings, params, registration) are covered here too because
// the walker derives inputs mechanically from their Zod schemas.

import { describe, expect, it } from "vitest";
import { TRPCError } from "@trpc/server";
import { appRouter } from "../index.js";
import { buildInput } from "./input-builder.js";
import { negativeFor } from "./schema-walker.js";

// biome-ignore-all lint/suspicious/noExplicitAny: tRPC introspection test

function inputParserOf(proc: any): any {
  const d = proc?._def;
  const p = d?.inputs?.[0] ?? d?.inputParser;
  return p && typeof p.safeParse === "function" ? p : null;
}

describe("tRPC wire boundary — every procedure (input enforcement)", () => {
  const caller = appRouter.createCaller({ headers: new Headers() });
  const procs = (appRouter._def as any).procedures as Record<string, any>;
  const withInput = Object.entries(procs).filter(([, d]) => inputParserOf(d));

  it(`covers all ${withInput.length} input-bearing procedures (expect >= 150)`, () => {
    expect(withInput.length).toBeGreaterThanOrEqual(150);
  });

  for (const [path, def] of withInput) {
    const parser = inputParserOf(def);
    const [routerAlias = "", method = ""] = path.split(".");

    it(`accepts derived-good input: ${path}`, () => {
      const input = buildInput(routerAlias, parser);
      const parsed = parser.safeParse(input);
      expect(
        parsed.success,
        `walker-derived input invalid for ${path}: ${JSON.stringify((parsed as any).error)}`,
      ).toBe(true);
    });

    const neg = negativeFor(parser);
    if (neg.badKey !== "") {
      it(`rejects corrupted input: ${path}`, async () => {
        const fn = ((caller as any)[routerAlias][method] as (i: unknown) => Promise<unknown>);
        await expect(fn(neg.input)).rejects.toThrow(TRPCError);
      });
    }
  }
});
